export function BulletsBackground() {
  return (
    <>
      <svg
        aria-hidden="true"
        className="absolute left-full translate-x-1/2"
        fill="none"
        height={404}
        viewBox="0 0 404 404"
        width={404}
      >
        <defs>
          <pattern
            height={20}
            id="85737c0e-0916-41d7-917f-596dc7edfa27"
            patternUnits="userSpaceOnUse"
            width={20}
            x={0}
            y={0}
          >
            <rect
              className="text-gray-200"
              fill="currentColor"
              height={4}
              width={4}
              x={0}
              y={0}
            />
          </pattern>
        </defs>
        <rect
          fill="url(#85737c0e-0916-41d7-917f-596dc7edfa27)"
          height={404}
          width={404}
        />
      </svg>
      <svg
        aria-hidden="true"
        className="absolute bottom-0 right-full -translate-x-1/2"
        fill="none"
        height={404}
        viewBox="0 0 404 404"
        width={404}
      >
        <defs>
          <pattern
            height={20}
            id="85737c0e-0916-41d7-917f-596dc7edfa27"
            patternUnits="userSpaceOnUse"
            width={20}
            x={0}
            y={0}
          >
            <rect
              className="text-gray-200"
              fill="currentColor"
              height={4}
              width={4}
              x={0}
              y={0}
            />
          </pattern>
        </defs>
        <rect
          fill="url(#85737c0e-0916-41d7-917f-596dc7edfa27)"
          height={404}
          width={404}
        />
      </svg>
    </>
  )
}
