language: node_js
node_js:
  - lts/*

branches:
  only:
    - master

before_script:
  - npm i -g firebase-tools

script:
  - npm run build

after_success:

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
