# Check PR for issues with Code Style
---
name: Check PR

on: pull_request

concurrency:
  group: check-pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check_code_style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Configure Vercel CLI Environments
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel env pull --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Check Format (Prettier)
        run: npm run check:format

      - name: Check Lint (ESLint)
        run: npm run lint

      - name: Check Build
        run: npm run build
