name: Cypress Tests

on: [push, deployment, deployment_status]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      # - name: Checkout
      #   uses: actions/checkout@v2
      # # Install NPM dependencies, cache them correctly
      # # and run all Cypress tests
      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     build: npm run build
      #     start: npm start
